# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[❯](yellow)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[line_break]
disabled = true

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) [@](yellow) "
disabled = false
show_always = true

[git_status]
disabled = true
